trigger:
- development

pool: 'Hetzner'

variables:
- group: docker_registry_credentials

steps:
- task: CmdLine@2
  displayName: Docker build image and push
  inputs:
    script: |
      DOCKER_BUILDKIT=0 docker build -f Dockerfile-dev -t registry.d.liehr.dev/solarapi:dev .

- task: CmdLine@2
  displayName: Docker registry login
  inputs:
    script: |
      docker login registry.d.liehr.dev -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)

- task: CmdLine@2
  displayName: Docker push image to hetzner
  inputs:
    script: |
      docker push -q registry.d.liehr.dev/solarapi:dev

- task: CmdLine@2
  displayName: Docker logout
  inputs:
    script: |
      docker logout registry.d.liehr.dev